### ISSUE TITLE
Not released .zip

### ISSUE THREAD

**Issue by SanSanMX** [MolPlantPathology/ScAnalyzer#1]
Hello, I want to use this tool but I can't find the .zip file, how can I install?

Thanks so much.

**Comment by NanneTaks** [comment]
Hi Enrique,

If you clone the repository and follow the steps in the README to install dependencies, it should work for you. 
Alternatively, you can set up a conda environment with the .yaml file and then run the python script.

Kind regards,
Nanne

**Comment by SanSanMX** [comment]
Thank you very much, you can close this issue.
